# Generated by Django 6.0.5 on 2026-05-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_expense_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='ph-package', max_length=50),
        ),
    ]
