# Generated by Django 6.0.5 on 2026-06-28 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_budget_daily_budget_budget_weekly_budget_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='dark', max_length=10)),
                ('sidebar_collapsed', models.BooleanField(default=False)),
                ('compact_mode', models.BooleanField(default=False)),
                ('animations', models.BooleanField(default=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('currency_symbol', models.CharField(default='$', max_length=5)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=20)),
                ('number_format', models.CharField(default='1,000.00', max_length=20)),
                ('budget_alerts', models.BooleanField(default=True)),
                ('weekly_report', models.BooleanField(default=True)),
                ('recurring_reminders', models.BooleanField(default=False)),
                ('auto_backup', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user settings',
            },
        ),
    ]
