# Generated by Django 5.2.14 on 2026-06-29 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_usersettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Income',
        ),
    ]
